# Generated by Django 4.0 on 2024-11-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Subject', models.CharField(max_length=250)),
                ('Marks', models.CharField(max_length=20)),
            ],
        ),
    ]
